version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      DB_NAME: pipedrive_assignment
      DB_USER: user
      DB_PASSWORD: pass
      HTTP_SERVER_PORT: 3000
    ports:
      - "3000:3000"
    command: /bin/sh -c "sleep 5; npm start"
  postgres:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pipedrive_assignment